/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentMarketplace {
  export type AgentStruct = {
    owner: AddressLike;
    metadataURI: string;
    active: boolean;
    capabilities: string[];
  };

  export type AgentStructOutput = [
    owner: string,
    metadataURI: string,
    active: boolean,
    capabilities: string[]
  ] & {
    owner: string;
    metadataURI: string;
    active: boolean;
    capabilities: string[];
  };

  export type TaskStruct = {
    id: BigNumberish;
    creator: AddressLike;
    assignedAgent: AddressLike;
    reward: BigNumberish;
    taskType: string;
    inputURI: string;
    status: BigNumberish;
    outputHash: BytesLike;
    outputURI: string;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type TaskStructOutput = [
    id: bigint,
    creator: string,
    assignedAgent: string,
    reward: bigint,
    taskType: string,
    inputURI: string,
    status: bigint,
    outputHash: string,
    outputURI: string,
    createdAt: bigint,
    completedAt: bigint
  ] & {
    id: bigint;
    creator: string;
    assignedAgent: string;
    reward: bigint;
    taskType: string;
    inputURI: string;
    status: bigint;
    outputHash: string;
    outputURI: string;
    createdAt: bigint;
    completedAt: bigint;
  };
}

export interface AgentMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignTask"
      | "cancelTask"
      | "createTask"
      | "getAgent"
      | "getAgentCapabilities"
      | "getTask"
      | "isAgentRegistered"
      | "nextTaskId"
      | "registerAgent"
      | "releasePayment"
      | "submitProof"
      | "updateAgentStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentStatusUpdated"
      | "PaymentReleased"
      | "ProofSubmitted"
      | "TaskAssigned"
      | "TaskCancelled"
      | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignTask",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCapabilities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTaskId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentStatus",
    values: [boolean]
  ): string;

  decodeFunctionResult(functionFragment: "assignTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAgentRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextTaskId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentStatus",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    owner: AddressLike,
    metadataURI: string,
    capabilities: string[]
  ];
  export type OutputTuple = [
    owner: string,
    metadataURI: string,
    capabilities: string[]
  ];
  export interface OutputObject {
    owner: string;
    metadataURI: string;
    capabilities: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusUpdatedEvent {
  export type InputTuple = [owner: AddressLike, active: boolean];
  export type OutputTuple = [owner: string, active: boolean];
  export interface OutputObject {
    owner: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, agent: string, reward: bigint];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    outputHash: BytesLike,
    outputURI: string
  ];
  export type OutputTuple = [
    taskId: bigint,
    agent: string,
    outputHash: string,
    outputURI: string
  ];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    outputHash: string;
    outputURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAssignedEvent {
  export type InputTuple = [taskId: BigNumberish, agent: AddressLike];
  export type OutputTuple = [taskId: bigint, agent: string];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    creator: AddressLike,
    taskType: string,
    inputURI: string,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    creator: string,
    taskType: string,
    inputURI: string,
    reward: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
    taskType: string;
    inputURI: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignTask: TypedContractMethod<
    [taskId: BigNumberish, agentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  createTask: TypedContractMethod<
    [taskType: string, inputURI: string],
    [bigint],
    "payable"
  >;

  getAgent: TypedContractMethod<
    [agentAddress: AddressLike],
    [AgentMarketplace.AgentStructOutput],
    "view"
  >;

  getAgentCapabilities: TypedContractMethod<
    [agentAddress: AddressLike],
    [string[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [AgentMarketplace.TaskStructOutput],
    "view"
  >;

  isAgentRegistered: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  nextTaskId: TypedContractMethod<[], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [metadataURI: string, capabilities: string[]],
    [void],
    "nonpayable"
  >;

  releasePayment: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [taskId: BigNumberish, outputHash: BytesLike, outputURI: string],
    [void],
    "nonpayable"
  >;

  updateAgentStatus: TypedContractMethod<
    [active: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, agentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [taskType: string, inputURI: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentAddress: AddressLike],
    [AgentMarketplace.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentCapabilities"
  ): TypedContractMethod<[agentAddress: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [AgentMarketplace.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgentRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextTaskId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [metadataURI: string, capabilities: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [taskId: BigNumberish, outputHash: BytesLike, outputURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAgentStatus"
  ): TypedContractMethod<[active: boolean], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusUpdated"
  ): TypedContractEvent<
    AgentStatusUpdatedEvent.InputTuple,
    AgentStatusUpdatedEvent.OutputTuple,
    AgentStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAssigned"
  ): TypedContractEvent<
    TaskAssignedEvent.InputTuple,
    TaskAssignedEvent.OutputTuple,
    TaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string,string[])": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusUpdated(address,bool)": TypedContractEvent<
      AgentStatusUpdatedEvent.InputTuple,
      AgentStatusUpdatedEvent.OutputTuple,
      AgentStatusUpdatedEvent.OutputObject
    >;
    AgentStatusUpdated: TypedContractEvent<
      AgentStatusUpdatedEvent.InputTuple,
      AgentStatusUpdatedEvent.OutputTuple,
      AgentStatusUpdatedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "ProofSubmitted(uint256,address,bytes32,string)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "TaskAssigned(uint256,address)": TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;
    TaskAssigned: TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;

    "TaskCancelled(uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCreated(uint256,address,string,string,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
